name: nrss

channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  # - cyrsoxs>=1.1.6.0
  - xarray
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-image
  - h5py
  - sphinx
  - pydata-sphinx-theme
